<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U7LEM7P" failures="2" tests="2" name="RetrymultipleFailedTestCases(failed)" time="0.084" errors="0" timestamp="2020-08-06T10:52:57 IST">
  <testcase classname="myTest.MyTestcases" name="test1" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTest.MyTestcases.test1(MyTestcases.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="myTest.MyTestcases" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at myTest.MyTestcases.test2(MyTestcases.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetrymultipleFailedTestCases(failed) -->
